title: Verification-Lab Conferences & Workshop Deadline Tracker
description: Countdowns to conference & workshop deadlines.
author: V-Lab

domain: "https://achintyadesai.github.io"
baseurl: "/vlab-deadlines"

twitter_username: achintyadesai
github_username: achintyadesai
github_repo: vlab-deadlines
ga_id:

markdown: kramdown

